---
# Location where configuration files will be stored.
config_dir: '~'

# Internet monitoring configuration.
monitoring_enable: true
monitoring_grafana_admin_password: "admin"
monitoring_speedtest_interval: 60m
monitoring_ping_interval: 1s
monitoring_ping_hosts:  # [URL];[HUMAN_READABLE_NAME]
  - https://www.google.com/;google.com
  - https://github.com/;github.com
  - https://www.apple.com/;apple.com
  - https://1.1.1.1/;cloudflare dns
  - https://8.8.8.8/;google dns
