---
- name: Ensure dependencies for docker-compose are installed (Debian).
  become: true
  ansible.builtin.apt:
    name:
      - libffi-dev
      - libssl-dev
      - python3-dev
      - python3-pip
      - git
      - rsync
      - pkg-config
    state: present
  when: ansible_facts.os_family == "Debian"

- name: Check for Docker Compose using Pip.
  ansible.builtin.pip:
    name: docker-compose
    state: present
    executable: pip3
  check_mode: true
  register: docker_compose_installed

- name: Debug
  ansible.builtin.debug:
    var: docker_compose_installed

- name: Check if Rust is already present.
  ansible.builtin.command: ~/.cargo/bin/rustc
  failed_when: false
  changed_when: false
  check_mode: false
  register: rust_command_result

- name: Download Rust install convenience script.
  ansible.builtin.get_url:
    url: https://sh.rustup.rs
    dest: /tmp/rustup.sh
    mode: 0775
  when: rust_command_result.rc != 0

- name: Run Docker install convenience script.
  ansible.builtin.command: /tmp/get-docker.sh
  environment:
    CHANNEL: stable
  when: rust_command_result.rc != 0

- name: Install Docker Compose using Pip.
  become: true
  ansible.builtin.pip:
    name: docker-compose
    state: present
    executable: pip3
  environment:
    PATH: /root/.cargo/bin:{{ ansible_env.PATH }}
    RUSTC: /root/.cargo/bin/rustc
  register: docker_compose_installation
